module_uncles = "Uncles"
mt_uncles = "Uncles"
card = "Card"
rank = "Rank"
crypto = "Crypto"
stegano = "Stegano"
programming = "Programming"
exploit = "Exploit"
math = "Math"
info = "Info"
rating = "Rating"
amount = "Cards"
err_uncle_self = "You cannot confront yourself."
err_uncle_no_cards = "One player has no cards available."
msg_uncle_won = "%s defeats %s and wins the %s card (%s vs %s)."
msg_uncle_won_drop = "%s defeats %s and wins the %s card (%s vs %s). Rare drop: %s."
